# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jyeR54tizxlO9hUVuVyQ6yiEud5TkpV
"""

import time
import random

def fractional_knapsack(items, maxvolume):
    # Sort items by value-to-weight ratio in decreasing order
    items = sorted(items, key=lambda i: i[0] / i[1], reverse=True)
    print("Items are", items)
    print("Maximum volume is", maxvolume)

    selected = []
    remaining_volume = maxvolume

    for item in items:
        if remaining_volume >= item[1]:
            selected.append(item)
            remaining_volume -= item[1]
        else:
            fraction = remaining_volume / item[1]
            selected.append((item[0] * fraction, item[1] * fraction))
            break

    return selected

# Example run
t0 = time.time_ns() // 1_000_000
items = [(random.randint(0, 100), random.randint(1, 100)) for _ in range(4)]
max_volume = random.randint(10, 100)

print(fractional_knapsack(items, max_volume))
t1 = time.time_ns() // 1_000_000
print(f'The Fractional Knapsack runtime is {t1 - t0} milliseconds')