# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jyeR54tizxlO9hUVuVyQ6yiEud5TkpV
"""

import time

def addNode(adj, v, e):
    adj[v].append(e)
    adj[e].append(v)
    return adj

def vertexColoring(adj, V):
    colorassigned = [-1] * V
    colorassigned[0] = 0
    usable = [False] * V

    for i in range(1, V):
        for j in adj[i]:
            if colorassigned[j] != -1:
                usable[colorassigned[j]] = True

        color = 0
        while color < V:
            if not usable[color]:
                break
            color += 1

        colorassigned[i] = color

        for j in adj[i]:
            if colorassigned[j] != -1:
                usable[colorassigned[j]] = False

    for i in range(V):
        color_name = ["Red", "Green", "Blue"]
        if colorassigned[i] < 3:
            print(f"Vertex {i+1} => Color {colorassigned[i]} ({color_name[colorassigned[i]]})")
        else:
            print(f"Vertex {i+1} => Color {colorassigned[i]}")

# Setup graph
G = [[] for _ in range(10)]
G = addNode(G, 0, 1)
G = addNode(G, 0, 4)
G = addNode(G, 0, 5)
G = addNode(G, 1, 2)
G = addNode(G, 1, 6)
G = addNode(G, 2, 3)
G = addNode(G, 2, 7)
G = addNode(G, 3, 4)
G = addNode(G, 3, 9)
G = addNode(G, 4, 8)
G = addNode(G, 5, 7)
G = addNode(G, 5, 9)
G = addNode(G, 6, 8)
G = addNode(G, 7, 8)

# Execute coloring
t0 = time.time_ns() // 1_000_000
vertexColoring(G, 10)
t1 = time.time_ns() // 1_000_000
print(f"Runtime of the Vertex Coloring algorithm is {t1 - t0} milliseconds")